import { createSeededRandom, shuffle } from '../generation/random'
import type { GenerationCharacter } from '../generation/types'
export interface DailyCharacterDefinition { id: string; name: string; avatar: string }
export const dailyCharacterCatalog: readonly DailyCharacterDefinition[] = [
  { id: 'ada', name: 'Ada', avatar: '🦋' }, { id: 'biel', name: 'Biel', avatar: '🦔' }, { id: 'cora', name: 'Cora', avatar: '🐦' }, { id: 'dario', name: 'Darío', avatar: '🦝' }, { id: 'elena', name: 'Elena', avatar: '🦢' }, { id: 'fabio', name: 'Fabio', avatar: '🦊' }, { id: 'gema', name: 'Gema', avatar: '🐚' }, { id: 'hugo', name: 'Hugo', avatar: '🦉' }, { id: 'iris', name: 'Iris', avatar: '🐈' }, { id: 'jules', name: 'Jules', avatar: '🦦' }, { id: 'kai', name: 'Kai', avatar: '🦎' }, { id: 'lara', name: 'Lara', avatar: '🐝' }, { id: 'milo', name: 'Milo', avatar: '🐺' }, { id: 'nerea', name: 'Nerea', avatar: '🪶' }, { id: 'olmo', name: 'Olmo', avatar: '🐢' }, { id: 'petra', name: 'Petra', avatar: '🦜' }, { id: 'quim', name: 'Quim', avatar: '🐙' }, { id: 'runa', name: 'Runa', avatar: '🦌' }
]
export function selectDailyCharacters(seed: number): GenerationCharacter[] { const selected = shuffle(dailyCharacterCatalog, createSeededRandom(seed)).slice(0, 6); const victimIndex = Math.floor(createSeededRandom((seed + 1) >>> 0)() * selected.length); return selected.map((character, index) => ({ ...character, isVictim: index === victimIndex })) }
const sameRoster = (left: readonly GenerationCharacter[], right: readonly GenerationCharacter[]) => { const rightIds = new Set(right.map(character => character.id)); return left.length === right.length && left.every(character => rightIds.has(character.id)) }
const replaceIfRepeated = (selected: GenerationCharacter[], previous: readonly GenerationCharacter[], seed: number) => { if (!sameRoster(selected, previous)) return selected; const previousIds = new Set(previous.map(character => character.id)); const replacement = shuffle(dailyCharacterCatalog.filter(character => !previousIds.has(character.id)), createSeededRandom((seed + 2) >>> 0))[0]; if (replacement) selected[selected.length - 1] = { ...replacement, isVictim: selected[selected.length - 1].isVictim }; return selected }
export function selectDailyCharactersForDate(date: Date, seedForDate: (date: Date) => number): GenerationCharacter[] { const seed = seedForDate(date); const previousDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - 1); const previousPreviousDate = new Date(previousDate.getFullYear(), previousDate.getMonth(), previousDate.getDate() - 1); const previous = replaceIfRepeated(selectDailyCharacters(seedForDate(previousDate)), selectDailyCharacters(seedForDate(previousPreviousDate)), seedForDate(previousDate)); return replaceIfRepeated(selectDailyCharacters(seed), previous, seed) }
