import { AppHeader } from '../components/AppHeader'
import './StatsScreen.css'
import { formatDifficultyStars } from '../game/difficulty'
import { loadNormalProgress } from '../game/persistence/normalProgress'
import { loadPlayerStats } from '../game/persistence/playerStats'
import { loadProgress } from '../game/persistence/progress'
import { loadInvestigationHistory } from '../game/persistence/investigationHistory'
import { achievementCatalog } from '../game/achievements/catalog'
import { loadAchievementProgress } from '../game/persistence/achievementProgress'
import { achievementCategoryLabel, achievementDisplayProgress, buildProfileSummary, getRecentAchievements } from '../game/achievements/presentation'

export function StatsScreen() {
  const context = { normalProgress: loadNormalProgress(), progress: loadProgress(), playerStats: loadPlayerStats(), investigationHistory: loadInvestigationHistory(), today: new Date() }
  const achievementProgress = loadAchievementProgress(), profile = buildProfileSummary(context, achievementProgress), statistics = profile.statistics
  const unlocked = new Map(achievementProgress.unlocked.map(item => [item.id, item.unlockedAt])), recentAchievements = getRecentAchievements(achievementProgress)
  return <main className="simple-screen stats-screen">
    <AppHeader back />
    <section className="simple-hero profile-hero"><p className="eyebrow">ARCHIVO DEL INVESTIGADOR</p><h1>PERFIL DEL INVESTIGADOR</h1><p>Tu progreso, rendimiento y logros en MysteryCases.</p><span className="profile-stamp">INVESTIGADOR</span></section>
    <section className="stats-summary" aria-label="Resumen de investigaciones">
      <article className="stats-card"><span>EXPEDIENTES CERRADOS</span><strong>{statistics.totalSolved}</strong></article><article className="stats-card"><span>CASOS NORMALES</span><strong>{statistics.normal.total} / 400</strong></article><article className="stats-card"><span>EXPEDIENTES IMPECABLES</span><strong>{statistics.performance.perfectUnique}</strong></article><article className="stats-card"><span>LOGROS</span><strong>{profile.unlocked} / 21</strong></article><article className="stats-card"><span>DIFICULTAD MÁXIMA</span><strong>{formatDifficultyStars(statistics.normal.highestUnlocked)}</strong></article><article className="stats-card"><span>RACHA DIARIA</span><strong>{statistics.daily.currentStreak} días</strong></article>
    </section>
    <section className="stats-section"><p className="eyebrow">ARCHIVO PRINCIPAL</p><article className="stats-card global-normal"><h2>{statistics.normal.total} / 400 {statistics.normal.total === 400 && <small>ARCHIVO COMPLETO</small>}</h2><progress value={statistics.normal.total} max={400} aria-label={`Archivo principal: ${statistics.normal.total} de 400`} /><p>{profile.normalPercent}% completado</p></article><div className="stats-grid">{statistics.normal.byDifficulty.map(item => <article className="stats-card progress-card" key={item.difficulty}><h2>{item.stars} <small>{item.completed === 80 ? 'DOMINADA' : item.unlocked ? 'DISPONIBLE' : 'BLOQUEADA'}</small></h2><p>{item.completed} / {item.max} expedientes</p><progress value={item.completed} max={item.max} aria-label={`Dificultad ${item.difficulty}: ${item.completed} de ${item.max}`} />{item.difficulty < 5 && !statistics.normal.byDifficulty[item.difficulty].unlocked && <small>Desbloqueo siguiente: {item.firstForty} / 40</small>}</article>)}</div></section>
    <div className="stats-grid"><section className="stats-card"><p className="eyebrow">CASO DIARIO</p><h2>Rachas</h2><p>Resueltos: <strong>{statistics.daily.completed}</strong></p><p>Racha actual: <strong>{statistics.daily.currentStreak} días</strong></p><p>Mejor racha: <strong>{statistics.daily.bestStreak} días</strong></p></section><section className="stats-card"><p className="eyebrow">CASO INFINITO</p><h2>Expedientes</h2><p>Distintos resueltos: <strong>{statistics.infinite.completed}</strong></p><p>Impecables registrados: <strong>{profile.infinitePerfect}</strong></p></section><section className="stats-card"><p className="eyebrow">AYUDAS DE INVESTIGACIÓN</p><h2>Consultas</h2><p>Revisiones: <strong>{statistics.hints.review}</strong></p><p>Pistas: <strong>{statistics.hints.exclusion}</strong></p><p>Comprobaciones: <strong>{statistics.hints.reveal}</strong></p><p>Total: <strong>{statistics.hints.total}</strong></p></section></div>
    <section className="stats-section"><p className="eyebrow">RENDIMIENTO REGISTRADO</p><article className="stats-card"><p>Investigaciones registradas: <strong>{statistics.performance.trackedUnique}</strong></p><p>Resoluciones registradas: <strong>{statistics.performance.trackedCompletions}</strong></p><p>Impecables distintos: <strong>{statistics.performance.perfectUnique}</strong></p><p>Runs impecables: <strong>{statistics.performance.perfectRuns}</strong></p><p>{profile.perfectRate === null ? 'Sin datos suficientes.' : `Tasa impecable registrada: ${profile.perfectRate}%`}</p><small>El rendimiento detallado se registra desde esta versión.</small></article></section>
    <section className="stats-section"><p className="eyebrow">ÚLTIMOS LOGROS</p><article className="stats-card">{recentAchievements.length ? <ul className="achievement-recent">{recentAchievements.map(item => <li key={item.id}><strong>{item.definition.title}</strong><small>{new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium' }).format(new Date(item.unlockedAt))}</small></li>)}</ul> : <p>Aún no has desbloqueado logros.</p>}</article></section>
    <section className="stats-section"><p className="eyebrow">LOGROS · {profile.unlocked} / 21</p><div className="achievement-gallery">{achievementCatalog.map(achievement => { const date = unlocked.get(achievement.id), progress = achievementDisplayProgress(achievement.id, context); return <article className={`achievement-card ${date ? 'unlocked' : 'locked'}`} key={achievement.id}><p>{achievementCategoryLabel(achievement.category)}</p><h2>{achievement.title}</h2><span>{date ? 'DESBLOQUEADO' : 'BLOQUEADO'}</span><div>{achievement.description}</div>{progress && <><progress value={progress.current} max={progress.target} aria-label={`${achievement.title}: ${progress.current} de ${progress.target}`} /><small>{progress.current} / {progress.target} · {progress.label}</small></>}{date && <small>{new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium' }).format(new Date(date))}</small>}</article> })}</div></section>
  </main>
}
