import { AppHeader } from '../components/AppHeader'
import './StatsScreen.css'
import { formatDifficultyStars } from '../game/difficulty'
import { achievementCatalog } from '../game/achievements/catalog'
import { achievementCategoryLabel, achievementDisplayProgress, buildProfileSummary, getRecentAchievements } from '../game/achievements/presentation'
import { NORMAL_CASE_COUNT, NORMAL_TOTAL_CASE_COUNT } from '../game/normal/constants'
import { loadAchievementProgress } from '../game/persistence/achievementProgress'
import { loadInvestigationHistory } from '../game/persistence/investigationHistory'
import { loadNormalProgress } from '../game/persistence/normalProgress'
import { loadPlayerStats } from '../game/persistence/playerStats'
import { loadProgress } from '../game/persistence/progress'

export function StatsScreen() {
  const context = { normalProgress: loadNormalProgress(), progress: loadProgress(), playerStats: loadPlayerStats(), investigationHistory: loadInvestigationHistory(), today: new Date() }
  const achievementProgress = loadAchievementProgress(), profile = buildProfileSummary(context, achievementProgress), statistics = profile.statistics
  const unlocked = new Map(achievementProgress.unlocked.map(item => [item.id, item.unlockedAt])), recent = getRecentAchievements(achievementProgress)
  return <main className="simple-screen stats-screen"><AppHeader back />
    <section className="simple-hero profile-hero"><p className="eyebrow">ARCHIVO DEL INVESTIGADOR</p><h1>PERFIL DEL INVESTIGADOR</h1><p>Tu progreso, rendimiento y logros en MysteryCases.</p><span className="profile-stamp">INVESTIGADOR</span></section>
    <section className="stats-summary" aria-label="Resumen de investigaciones"><article className="stats-card"><span>EXPEDIENTES CERRADOS</span><strong>{statistics.totalSolved}</strong></article><article className="stats-card"><span>CASOS NORMALES</span><strong>{statistics.normal.total} / {NORMAL_TOTAL_CASE_COUNT}</strong></article><article className="stats-card"><span>EXPEDIENTES IMPECABLES</span><strong>{statistics.performance.perfectUnique}</strong></article><article className="stats-card"><span>LOGROS</span><strong>{profile.unlocked} / 21</strong></article><article className="stats-card"><span>DIFICULTAD MÁXIMA</span><strong>{formatDifficultyStars(statistics.normal.highestUnlocked)}</strong></article><article className="stats-card"><span>RACHA DIARIA</span><strong>{statistics.daily.currentStreak} días</strong></article></section>
    <section className="stats-section"><p className="eyebrow">ARCHIVO PRINCIPAL</p><article className="stats-card global-normal"><h2>{statistics.normal.total} / {NORMAL_TOTAL_CASE_COUNT} {statistics.normal.total === NORMAL_TOTAL_CASE_COUNT && <small>ARCHIVO COMPLETO</small>}</h2><progress value={statistics.normal.total} max={NORMAL_TOTAL_CASE_COUNT} aria-label={`Archivo principal: ${statistics.normal.total} de ${NORMAL_TOTAL_CASE_COUNT}`} /><p>{profile.normalPercent}% completado</p></article><div className="stats-grid">{statistics.normal.byDifficulty.map(item => { const state = item.completed === NORMAL_CASE_COUNT ? 'mastered' : item.unlocked ? 'available' : 'locked'; return <article className={`stats-card progress-card difficulty-${state}`} key={item.difficulty}><h2>{item.stars} <small>{state === 'mastered' ? 'DOMINADA' : state === 'available' ? 'DISPONIBLE' : 'BLOQUEADA'}</small></h2><p>{item.completed} / {item.max} expedientes</p><progress value={item.completed} max={item.max} aria-label={`Dificultad ${item.difficulty}: ${item.completed} de ${item.max}`} />{item.difficulty < 5 && !statistics.normal.byDifficulty[item.difficulty].unlocked && <small>Desbloqueo siguiente: {item.unlockCases} / {NORMAL_CASE_COUNT}</small>}</article> })}</div></section>
    <section className="stats-section"><p className="eyebrow">ÚLTIMOS LOGROS</p><article className="stats-card">{recent.length ? <ul className="achievement-recent">{recent.map(item => <li key={item.id}><strong>{item.definition.title}</strong><small>{new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium' }).format(new Date(item.unlockedAt))}</small></li>)}</ul> : <p>Aún no has desbloqueado logros.</p>}</article></section>
    <section className="stats-section"><p className="eyebrow">LOGROS · {profile.unlocked} / 21</p><div className="achievement-gallery">{achievementCatalog.map(achievement => { const date = unlocked.get(achievement.id), progress = achievementDisplayProgress(achievement.id, context); return <article className={`achievement-card ${date ? 'unlocked' : 'locked'}`} key={achievement.id}><p>{achievementCategoryLabel(achievement.category)}</p><h2>{achievement.title}</h2><span>{date ? 'DESBLOQUEADO' : 'BLOQUEADO'}</span><div>{achievement.description}</div>{progress && <><progress value={progress.current} max={progress.target} aria-label={`${achievement.title}: ${progress.current} de ${progress.target}`} /><small>{progress.current} / {progress.target} · {progress.label}</small></>}{date && <small>{new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium' }).format(new Date(date))}</small>}</article> })}</div></section>
  </main>
}
