import { describe, expect, it } from 'vitest'
import { achievementCatalog } from '../achievements/catalog'
import { evaluateAchievements } from '../achievements/evaluator'
import { ACHIEVEMENT_PROGRESS_KEY, loadAchievementProgress, reconcileAchievements } from '../persistence/achievementProgress'
import { NORMAL_CASE_COUNT, type NormalModeProgress } from '../persistence/normalProgress'
import { type Progress } from '../persistence/progress'
import { type PlayerStats } from '../persistence/playerStats'
import { type InvestigationHistory } from '../persistence/investigationHistory'
import { MemoryStorage } from './storage'
import { loadPlayerStats, savePlayerStats } from '../persistence/playerStats'
import { ACHIEVEMENT_TOAST_DURATION_MS, dequeueAchievement, enqueueAchievements, getCurrentAchievement } from '../achievements/toastQueue'

const normal = (counts: Partial<Record<1 | 2 | 3 | 4 | 5, number>> = {}): NormalModeProgress => ({ saveVersion: 1, selectedDifficulty: 1, completedCaseNumbersByDifficulty: { 1: Array.from({ length: counts[1] ?? 0 }, (_, index) => index + 1), 2: Array.from({ length: counts[2] ?? 0 }, (_, index) => index + 1), 3: Array.from({ length: counts[3] ?? 0 }, (_, index) => index + 1), 4: Array.from({ length: counts[4] ?? 0 }, (_, index) => index + 1), 5: Array.from({ length: counts[5] ?? 0 }, (_, index) => index + 1) } })
const context = (overrides: Partial<{ normalProgress: NormalModeProgress; progress: Progress; playerStats: PlayerStats; investigationHistory: InvestigationHistory; today: Date }> = {}) => ({ normalProgress: normal(), progress: { saveVersion: 1 as const, completedCaseIds: [] }, playerStats: { saveVersion: 1 as const, completedInfiniteCaseIds: [], hintsUsed: { review: 0, exclusion: 0, reveal: 0 } }, investigationHistory: { saveVersion: 1 as const, records: [] }, today: new Date('2026-09-15T12:00:00Z'), ...overrides })
const ids = (value: ReturnType<typeof context>) => evaluateAchievements(value).map(item => item.id)

describe('achievements', () => {
  it('has exactly 21 unique, complete catalog definitions', () => { expect(achievementCatalog).toHaveLength(21); expect(new Set(achievementCatalog.map(item => item.id)).size).toBe(21); expect(achievementCatalog.every(item => item.title && item.description && ['progress', 'skill', 'daily', 'infinite'].includes(item.category))).toBe(true) })
  it.each([[1, 'first-investigation'], [10, 'investigations-10'], [50, 'investigations-50'], [100, 'investigations-100']] as const)('unlocks unique investigation threshold %i without counting replays', (count, achievement) => {
    const completed = Array.from({ length: count }, (_, index) => `infinite-d1-s${index}`)
    const before = count > 1 ? completed.slice(0, -1) : []
    const playerStats = (caseIds: string[]): PlayerStats => ({ saveVersion: 1, completedInfiniteCaseIds: caseIds, hintsUsed: { review: 0, exclusion: 0, reveal: 0 } })
    expect(ids(context({ playerStats: playerStats(before) }))).not.toContain(achievement)
    expect(ids(context({ playerStats: playerStats(completed) }))).toContain(achievement)
  })
  it('requires all active cases for each Normal difficulty and all five for the archive', () => { expect(ids(context({ normalProgress: normal({ 1: NORMAL_CASE_COUNT - 1 }) }))).not.toContain('normal-d1-complete'); expect(ids(context({ normalProgress: normal({ 1: NORMAL_CASE_COUNT }) }))).toContain('normal-d1-complete'); expect(ids(context({ normalProgress: normal({ 5: NORMAL_CASE_COUNT }) }))).toContain('normal-d5-complete'); expect(ids(context({ normalProgress: normal({ 1: NORMAL_CASE_COUNT, 2: NORMAL_CASE_COUNT, 3: NORMAL_CASE_COUNT, 4: NORMAL_CASE_COUNT }) }))).not.toContain('normal-all-75'); expect(ids(context({ normalProgress: normal({ 1: NORMAL_CASE_COUNT, 2: NORMAL_CASE_COUNT, 3: NORMAL_CASE_COUNT, 4: NORMAL_CASE_COUNT, 5: NORMAL_CASE_COUNT }) }))).toContain('normal-all-75') })
  it('unlocks all difficulties only through the real Normal chain', () => { expect(ids(context({ normalProgress: normal({ 1: 40, 2: 40, 3: 40 }) }))).not.toContain('all-difficulties-unlocked'); expect(ids(context({ normalProgress: normal({ 1: 40, 2: 40, 3: 40, 4: 40 }) }))).toContain('all-difficulties-unlocked') })
  it.each([[1, 'normal-d1-complete'], [2, 'normal-d2-complete'], [3, 'normal-d3-complete'], [4, 'normal-d4-complete'], [5, 'normal-d5-complete']] as const)('requires fifteen cases for Normal D%i', (difficulty, achievement) => { expect(ids(context({ normalProgress: normal({ [difficulty]: NORMAL_CASE_COUNT - 1 }) }))).not.toContain(achievement); expect(ids(context({ normalProgress: normal({ [difficulty]: NORMAL_CASE_COUNT }) }))).toContain(achievement) })
  it('uses only distinct perfect history records for skill achievements', () => {
    const record = (id: string, difficulty = 1) => ({ logicalId: id, mode: 'normal' as const, difficulty: difficulty as 1 | 5, firstCompletedAt: '2026-09-15T00:00:00Z', lastCompletedAt: '2026-09-15T00:00:00Z', completions: 10, perfectCompletions: 10, lastAssistUsage: { review: 0, exclusion: 0, positionChecks: 0, total: 0 }, bestAssistUsage: { review: 0, exclusion: 0, positionChecks: 0, total: 0 } })
    const single = { saveVersion: 1 as const, records: [record('normal-d1-c01')] }
    const ten = { saveVersion: 1 as const, records: Array.from({ length: 10 }, (_, index) => record(`normal-d1-c${String(index + 1).padStart(2, '0')}`)) }
    expect(ids(context({ investigationHistory: single }))).toContain('first-perfect')
    expect(ids(context({ investigationHistory: single }))).not.toContain('perfect-10')
    expect(ids(context({ investigationHistory: ten }))).toContain('perfect-10')
    expect(ids(context({ investigationHistory: { saveVersion: 1, records: [record('infinite-d5-s1', 5)] } }))).toContain('perfect-d5')
  })
  it('persists valid unlocks once, keeps the earliest duplicate date and rejects corrupt saves', () => { const storage = new MemoryStorage(), eligible = achievementCatalog.slice(0, 2); const first = reconcileAchievements(eligible, storage, new Date('2026-09-15T10:00:00Z')); expect(first.newlyUnlocked.map(item => item.id)).toEqual(eligible.map(item => item.id)); expect(reconcileAchievements(eligible, storage, new Date()).newlyUnlocked).toEqual([]); storage.setItem(ACHIEVEMENT_PROGRESS_KEY, JSON.stringify({ saveVersion: 1, unlocked: [{ id: 'first-investigation', unlockedAt: '2026-09-16T00:00:00Z' }, { id: 'first-investigation', unlockedAt: '2026-09-14T00:00:00Z' }, { id: 'fake', unlockedAt: '2026-09-01T00:00:00Z' }] })); expect(loadAchievementProgress(storage).unlocked).toEqual([{ id: 'first-investigation', unlockedAt: '2026-09-14T00:00:00Z' }]); storage.setItem(ACHIEVEMENT_PROGRESS_KEY, '{'); expect(loadAchievementProgress(storage).unlocked).toEqual([]) })
  it('uses historical Daily best streak even after the current streak is broken', () => { const dates = (count: number) => Array.from({ length: count }, (_, index) => `daily-2026-01-${String(index + 1).padStart(2, '0')}`); for (const [count, achievement] of [[2, 'daily-streak-3'], [3, 'daily-streak-3'], [7, 'daily-streak-7'], [30, 'daily-streak-30']] as const) { const available = ids(context({ progress: { saveVersion: 1, completedCaseIds: dates(count) }, today: new Date('2026-03-01T12:00:00Z') })); expect(available.includes(achievement)).toBe(count !== 2) } })
  it('uses persisted unique Infinite IDs for the 0/1/9/10/49/50 thresholds', () => { const storage = new MemoryStorage(); for (const count of [0, 1, 9, 10, 49, 50]) { const ids = Array.from({ length: count }, (_, index) => `infinite-d1-s${index}`); savePlayerStats({ saveVersion: 1, completedInfiniteCaseIds: [...ids, ...ids], hintsUsed: { review: 0, exclusion: 0, reveal: 0 } }, storage); const available = evaluateAchievements(context({ playerStats: loadPlayerStats(storage) })).map(item => item.id); expect(available.includes('first-infinite')).toBe(count >= 1); expect(available.includes('infinite-10')).toBe(count >= 10); expect(available.includes('infinite-50')).toBe(count >= 50) } })
  it('keeps legacy progress available for a silent backfill without mutating it', () => { const storage = new MemoryStorage(), legacy = context({ normalProgress: normal({ 1: 50 }), progress: { saveVersion: 1, completedCaseIds: Array.from({ length: 50 }, (_, index) => `daily-2026-01-${String(index + 1).padStart(2, '0')}`) } }), before = structuredClone(legacy); const result = reconcileAchievements(evaluateAchievements(legacy), storage, new Date('2026-09-15T00:00:00Z')); expect(result.newlyUnlocked.map(item => item.id)).toEqual(expect.arrayContaining(['first-investigation', 'investigations-10', 'investigations-50'])); expect(legacy).toEqual(before); expect(loadAchievementProgress(storage).unlocked).not.toEqual([]) })
  it('keeps achievement notifications in FIFO order', () => { const [first, second, third] = achievementCatalog.slice(0, 3), queue = enqueueAchievements([], [first, second, third]); expect(ACHIEVEMENT_TOAST_DURATION_MS).toBe(4000); expect(getCurrentAchievement(queue)).toBe(first); expect(getCurrentAchievement(dequeueAchievement(queue))).toBe(second); expect(getCurrentAchievement(dequeueAchievement(dequeueAchievement(queue)))).toBe(third) })
})
