import { describe, expect, it } from 'vitest'
import { achievementCategoryLabel, achievementDisplayProgress, buildProfileSummary, getRecentAchievements } from '../achievements/presentation'
import type { AchievementContext } from '../achievements/evaluator'
import type { AchievementProgress } from '../persistence/achievementProgress'

const context = (normalCounts: [number, number, number, number, number] = [0, 0, 0, 0, 0], daily: string[] = [], infinite: string[] = [], records: AchievementContext['investigationHistory']['records'] = []): AchievementContext => ({ normalProgress: { saveVersion: 1, selectedDifficulty: 1, completedCaseNumbersByDifficulty: { 1: Array.from({ length: normalCounts[0] }, (_, i) => i + 1), 2: Array.from({ length: normalCounts[1] }, (_, i) => i + 1), 3: Array.from({ length: normalCounts[2] }, (_, i) => i + 1), 4: Array.from({ length: normalCounts[3] }, (_, i) => i + 1), 5: Array.from({ length: normalCounts[4] }, (_, i) => i + 1) } }, progress: { saveVersion: 1, completedCaseIds: daily }, playerStats: { saveVersion: 1, completedInfiniteCaseIds: infinite, hintsUsed: { review: 0, exclusion: 0, reveal: 0 } }, investigationHistory: { saveVersion: 1, records }, today: new Date('2026-03-01T12:00:00Z') })
const record = (id: string, difficulty = 1, mode: 'normal' | 'infinite' = 'normal') => ({ logicalId: id, mode, difficulty: difficulty as 1 | 5, firstCompletedAt: '2026-01-01T00:00:00Z', lastCompletedAt: '2026-01-01T00:00:00Z', completions: 20, perfectCompletions: 20, lastAssistUsage: { review: 0, exclusion: 0, positionChecks: 0, total: 0 }, bestAssistUsage: { review: 0, exclusion: 0, positionChecks: 0, total: 0 } })
const progress = (id: Parameters<typeof achievementDisplayProgress>[0], value: AchievementContext) => achievementDisplayProgress(id, value)!

describe('achievement presentation', () => {
  it('maps category labels and clamps investigation/Normal progress', () => { expect(['progress', 'skill', 'daily', 'infinite'].map(value => achievementCategoryLabel(value as 'progress'))).toEqual(['PROGRESO', 'HABILIDAD', 'DIARIO', 'INFINITO']); expect(progress('investigations-10', context([0, 0, 0, 0, 0], [], Array.from({ length: 7 }, (_, i) => `infinite-d1-s${i}`)))).toMatchObject({ current: 7, target: 10 }); expect(progress('investigations-10', context([0, 0, 0, 0, 0], [], Array.from({ length: 15 }, (_, i) => `infinite-d1-s${i}`)))).toMatchObject({ current: 10, target: 10 }); expect(progress('normal-d3-complete', context([0, 0, 42, 0, 0]))).toMatchObject({ current: 42, target: 80 }); expect(progress('normal-all-400', context([80, 80, 77, 0, 0]))).toMatchObject({ current: 237, target: 400 }) })
  it('uses distinct perfect records, daily best streaks and Infinite IDs', () => { const perfect = [record('normal-d1-c01'), record('normal-d1-c02'), record('normal-d1-c03')]; expect(progress('perfect-10', context([0, 0, 0, 0, 0], [], [], perfect))).toMatchObject({ current: 3, target: 10 }); expect(progress('perfect-d5', context())).toMatchObject({ current: 0, target: 1 }); expect(progress('perfect-d5', context([0, 0, 0, 0, 0], [], [], [record('infinite-d5-s1', 5, 'infinite')]))).toMatchObject({ current: 1, target: 1 }); const days = Array.from({ length: 10 }, (_, i) => `daily-2026-01-${String(i + 1).padStart(2, '0')}`); expect(progress('daily-streak-7', context([0, 0, 0, 0, 0], days))).toMatchObject({ current: 7, target: 7 }); expect(progress('infinite-10', context([0, 0, 0, 0, 0], [], Array.from({ length: 12 }, (_, i) => `infinite-d1-s${i}`)))).toMatchObject({ current: 10, target: 10 }) })
  it('sorts recent achievements without mutation and builds a safe profile summary', () => { const unlocked: AchievementProgress = { saveVersion: 1, unlocked: ['first-investigation', 'investigations-10', 'investigations-50', 'first-perfect', 'first-daily'].map((id, i) => ({ id: id as AchievementProgress['unlocked'][number]['id'], unlockedAt: `2026-01-0${i + 1}T00:00:00Z` })) }; const before = structuredClone(unlocked); expect(getRecentAchievements(unlocked).map(item => item.id)).toEqual(['first-daily', 'first-perfect', 'investigations-50']); expect(unlocked).toEqual(before); const full = context([80, 80, 80, 80, 80], [], [], [record('normal-d1-c01'), record('normal-d1-c02'), record('normal-d1-c03'), { ...record('infinite-d1-s1', 1, 'infinite'), bestAssistUsage: { review: 1, exclusion: 0, positionChecks: 0, total: 1 } }, ...Array.from({ length: 6 }, (_, i) => ({ ...record(`normal-d1-c${i + 10}`), bestAssistUsage: { review: 1, exclusion: 0, positionChecks: 0, total: 1 } }))]); const summary = buildProfileSummary(full, unlocked); expect(summary).toMatchObject({ unlocked: 5, normalPercent: 100, perfectRate: 30, infinitePerfect: 0 }); expect(buildProfileSummary(context(), { saveVersion: 1, unlocked: [] }).perfectRate).toBeNull() })
})
