import { describe, expect, it } from 'vitest'
import { analyzeCase } from '../analysis'
import { dailyCharacterCatalog, dailyCharacterGroupA, selectDailyCharactersForDate } from '../daily/characters'
import { getDailyCaseId, getDailyDateKey, getDailySeed } from '../daily/date'
import { clearDailyCaseCache, generateDailyCase, getCachedDailyCase } from '../daily/generator'
import { getCaseSaveKey } from '../persistence/caseSave'
import { isCaseCompleted, markCaseCompleted } from '../persistence/progress'
import { findKiller } from '../rules'
import { solveCase } from '../solver'
import { validateCaseDefinition } from '../validation'
import { case001 } from '../../data/cases/case001'

const memory = () => { const data = new Map<string, string>(); return { getItem: (key: string) => data.get(key) ?? null, setItem: (key: string, value: string) => data.set(key, value), removeItem: (key: string) => data.delete(key), clear: () => data.clear(), key: () => null, get length() { return data.size } } as Storage }
const dateA = new Date(2026, 8, 8, 12), dateB = new Date(2026, 8, 9, 12)
describe('daily case', () => {
  it.each([1, 2, 3, 4, 5] as const)('escala Daily de forma válida en dificultad %s', difficulty => { const generated = generateDailyCase(dateA, difficulty), clues = generated.caseData.characters.flatMap(character => character.clues), negative = (type: string) => type === 'notZone' || type === 'notOnObject' || type === 'notBesideObject'; expect(generated.caseData.rows).toBe(5 + difficulty); expect(generated.caseData.columns).toBe(5 + difficulty); expect(generated.caseData.characters).toHaveLength(5 + difficulty); expect(generated.caseData.characters.every(character => character.clues.length >= 2 && character.clues.some(clue => !negative(clue.type)) && !(character.clues.some(clue => clue.type === 'row') && character.clues.some(clue => clue.type === 'column')))).toBe(true); expect(clues.filter(clue => negative(clue.type)).length / clues.length).toBeLessThanOrEqual(.4); expect(validateCaseDefinition(generated.caseData)).toEqual([]); expect(solveCase(generated.caseData).solutionsFound).toBe(1); expect(analyzeCase(generated.caseData)).toMatchObject({ status: 'unique', matchesCanonical: true }); expect(findKiller(generated.caseData, generated.caseData.solution)?.id).toBe(generated.killerId) })
  it('deriva fecha, id y seed local determinista', () => { expect(getDailyDateKey(dateA)).toBe('2026-09-08'); expect(getDailyCaseId(dateA)).toBe('daily-2026-09-08'); expect(getDailySeed(dateA)).not.toBe(getDailySeed(dateB)); for (const date of [dateA, dateB, new Date(2026, 9, 1, 12)]) { const seed = getDailySeed(date); expect(Number.isInteger(seed)).toBe(true); expect(seed).toBeGreaterThanOrEqual(0); expect(seed).toBeLessThanOrEqual(4294967295) } })
  it('cumple catálogo, roster par/impar y víctima única', () => { expect(dailyCharacterCatalog.length).toBeGreaterThanOrEqual(18); expect(new Set(dailyCharacterCatalog.map(item => item.id)).size).toBe(dailyCharacterCatalog.length); expect(dailyCharacterCatalog.every(item => item.name.trim() !== '' && item.avatar.trim() !== '')).toBe(true); for (const date of [dateA, dateB]) { const roster = selectDailyCharactersForDate(date), a = roster.filter(item => dailyCharacterGroupA.some(candidate => candidate.id === item.id)); expect(roster).toHaveLength(6); expect(new Set(roster.map(item => item.id)).size).toBe(6); expect(roster.filter(item => item.isVictim)).toHaveLength(1); const day = Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86400000); expect(a).toHaveLength(day % 2 === 0 ? 4 : 2) } expect(selectDailyCharactersForDate(dateA)).toEqual(selectDailyCharactersForDate(dateA)) })
  it('mantiene roster distinto durante 365 días consecutivos', () => { let previous = new Set(selectDailyCharactersForDate(new Date(2026, 0, 1, 12)).map(character => character.id)); for (let offset = 1; offset <= 365; offset += 1) { const current = new Set(selectDailyCharactersForDate(new Date(2026, 0, 1 + offset, 12)).map(character => character.id)); expect(current).not.toEqual(previous); previous = current } })
  it.each([dateA, dateB, new Date(2026, 9, 1, 12)])('genera un Daily válido para %s', date => { const generated = generateDailyCase(date); const clues = generated.caseData.characters.flatMap(character => character.clues); const negative = (type: string) => type === 'notZone' || type === 'notOnObject' || type === 'notBesideObject'; expect(generated.caseData.characters.every(character => character.clues.length >= 2 && character.clues.some(clue => !negative(clue.type)) && !(character.clues.some(clue => clue.type === 'row') && character.clues.some(clue => clue.type === 'column')))).toBe(true); const victim = generated.caseData.characters.find(character => character.isVictim); expect(victim?.clues.length).toBeGreaterThanOrEqual(2); expect(victim?.clues.some(clue => !negative(clue.type))).toBe(true); expect(clues.filter(clue => negative(clue.type)).length / clues.length).toBeLessThanOrEqual(.4); expect(validateCaseDefinition(generated.caseData)).toEqual([]); expect(solveCase(generated.caseData).solutionsFound).toBe(1); const analysis = analyzeCase(generated.caseData); expect(analysis.status).toBe('unique'); expect(analysis.matchesCanonical).toBe(true); const killer = findKiller(generated.caseData, generated.caseData.solution); expect(killer).not.toBeNull(); expect(killer?.id).toBe(generated.killerId); expect(generated.seedOffset).toBeGreaterThanOrEqual(0); expect(generated.seedOffset).toBeLessThan(100); expect(generated.effectiveSeed).toBe((generated.baseSeed + generated.seedOffset) >>> 0) })
  it('es reproducible, diferencia días y cachea por fecha', () => { clearDailyCaseCache(); const a = generateDailyCase(dateA), b = generateDailyCase(dateA), other = generateDailyCase(dateB); expect(a).toEqual(b); expect(a.caseData.id).not.toBe(other.caseData.id); expect(new Set(a.caseData.characters.map(c => c.id))).not.toEqual(new Set(other.caseData.characters.map(c => c.id))); expect(a.caseData.board).not.toEqual(other.caseData.board); expect(getCachedDailyCase(dateA)).toBe(getCachedDailyCase(dateA)); expect(getCachedDailyCase(dateA).caseData.id).not.toBe(getCachedDailyCase(dateB).caseData.id) })
  it('separa progreso y save keys entre días', () => { const storage = memory(), idA = getDailyCaseId(dateA), idB = getDailyCaseId(dateB); expect(isCaseCompleted(idA, storage)).toBe(false); expect(isCaseCompleted(idB, storage)).toBe(false); markCaseCompleted(idA, storage); expect(isCaseCompleted(idA, storage)).toBe(true); expect(isCaseCompleted(idB, storage)).toBe(false); expect(getCaseSaveKey(idA)).toBe('mystery-cases-daily-2026-09-08'); expect(getCaseSaveKey(idA)).not.toBe(getCaseSaveKey(idB)) })
  it('no muta case001 ni el catálogo', () => { const originalCase = structuredClone(case001), originalCatalog = structuredClone(dailyCharacterCatalog); generateDailyCase(dateA); expect(case001).toEqual(originalCase); expect(dailyCharacterCatalog).toEqual(originalCatalog) })
})
