import { describe, expect, it } from 'vitest'
import { analyzeCase } from '../analysis'
import { evaluateClue } from '../clues'
import { createGenerationTemplate } from '../generation/template'
import { generatePuzzle } from '../generation/generator'
import { findKiller, getCell, placementsEqual } from '../rules'
import { solveCase } from '../solver'
import { validateCaseDefinition } from '../validation'
import { case001 } from '../../data/cases/case001'
import type { GenerationTemplate } from '../generation/types'

const template = () => createGenerationTemplate(case001)
const canonical = (generated: ReturnType<typeof generatePuzzle>) => analyzeCase(generated.caseData).status === 'unique' && analyzeCase(generated.caseData).matchesCanonical === true
describe('generatePuzzle', () => {
  it('es reproducible para la misma seed', () => { const first = generatePuzzle(template(), { seed: 12345 }); const second = generatePuzzle(template(), { seed: 12345 }); expect(placementsEqual(first.caseData.solution, second.caseData.solution)).toBe(true); expect(first.caseData.characters.map(c => c.clues.map(clue => clue.id))).toEqual(second.caseData.characters.map(c => c.clues.map(clue => clue.id))); expect(first.killerId).toBe(second.killerId); expect(first.caseData.id).toBe(second.caseData.id) })
  it('las seeds verificadas 12345 y 67890 producen resultados distintos', () => { const first = generatePuzzle(template(), { seed: 12345 }); const second = generatePuzzle(template(), { seed: 67890 }); const firstClues = first.caseData.characters.flatMap(character => character.clues.map(clue => clue.id)); const secondClues = second.caseData.characters.flatMap(character => character.clues.map(clue => clue.id)); expect(placementsEqual(first.caseData.solution, second.caseData.solution) && firstClues.join('|') === secondClues.join('|')).toBe(false) })
  it('genera puzzles válidos, únicos y con pistas verdaderas', () => { const generated = generatePuzzle(template(), { seed: 12345 }); expect(validateCaseDefinition(generated.caseData)).toEqual([]); expect(solveCase(generated.caseData).solutionsFound).toBe(1); expect(canonical(generated)).toBe(true); expect(generated.killerId).toBe(findKiller(generated.caseData, generated.caseData.solution)?.id); for (const character of generated.caseData.characters) for (const clue of character.clues) expect(evaluateClue(clue, character.id, generated.caseData, generated.caseData.solution)).toBe('satisfied') })
  it.each([1, 2, 3, 10, 42])('genera una solución válida para seed %s', seed => { const generated = generatePuzzle(template(), { seed }); expect(canonical(generated)).toBe(true); expect(findKiller(generated.caseData, generated.caseData.solution)).not.toBeNull(); const rows = new Set(generated.caseData.solution.map(p => p.position.row)); const columns = new Set(generated.caseData.solution.map(p => p.position.column)); expect(rows.size).toBe(generated.caseData.characters.length); expect(columns.size).toBe(generated.caseData.characters.length); for (const placement of generated.caseData.solution) expect(getCell(generated.caseData.board, placement.position)?.occupiable).toBe(true) })
  it('respeta minCluesPerCharacter y acepta cero', () => { const defaultGenerated = generatePuzzle(template(), { seed: 12345 }); expect(defaultGenerated.caseData.characters.every(c => c.clues.length >= 1)).toBe(true); expect(generatePuzzle(template(), { seed: 12345, minCluesPerCharacter: 0 }).caseData.characters.length).toBe(6) })
  it('no deja pistas eliminables legalmente tras minimizar', () => { const generated = generatePuzzle(template(), { seed: 12345 }); for (const character of generated.caseData.characters) for (const clue of character.clues) { if (character.clues.length <= 1) continue; const trial = structuredClone(generated.caseData); const trialCharacter = trial.characters.find(candidate => candidate.id === character.id); if (!trialCharacter) throw new Error('Personaje de prueba no encontrado.'); trialCharacter.clues = trialCharacter.clues.filter(candidate => candidate.id !== clue.id); const analysis = analyzeCase(trial); expect(analysis.status === 'unique' && analysis.matchesCanonical === true).toBe(false) } })
  it.each([-1, 1.5, Number.NaN, Number.POSITIVE_INFINITY, 4294967296])('rechaza seed inválida %s', seed => expect(() => generatePuzzle(template(), { seed })).toThrow('seed must be a uint32 integer.'))
  it.each([{ maxPlacementAttempts: 0 }, { maxPlacementAttempts: -1 }, { maxPlacementAttempts: 1.5 }, { minCluesPerCharacter: -1 }, { minCluesPerCharacter: 1.5 }, { minCluesPerCharacter: Number.NaN }, { minCluesPerCharacter: Number.POSITIVE_INFINITY }])('rechaza opciones inválidas', options => expect(() => generatePuzzle(template(), { seed: 12345, ...options })).toThrow())
  it('no muta la plantilla ni case001', () => { const source = template(); const templateBefore = structuredClone(source); const caseBefore = structuredClone(case001); generatePuzzle(source, { seed: 12345 }); expect(source).toEqual(templateBefore); expect(case001).toEqual(caseBefore) })
  it('falla de forma acotada si nunca puede existir un asesino único', () => { const impossible: GenerationTemplate = { id: 'impossible', title: '', intro: '', difficulty: '', rows: 3, columns: 3, zones: [{ id: 'one', name: 'Una', tone: 'one' }], board: Array.from({ length: 9 }, (_, index) => ({ row: Math.floor(index / 3) + 1, column: index % 3 + 1, zoneId: 'one', occupiable: true })), characters: [{ id: 'victim', name: 'V', avatar: '', isVictim: true }, { id: 'a', name: 'A', avatar: '', isVictim: false }, { id: 'b', name: 'B', avatar: '', isVictim: false }] }; expect(() => generatePuzzle(impossible, { seed: 1, maxPlacementAttempts: 40 })).toThrow('Unable to generate a valid placement with a unique killer.') })
})
