import { describe, expect, it } from 'vitest'
import { analyzeCase } from '../analysis'
import { getDifficultyPreset } from '../difficultyPresets'
import { clearInfiniteCaseCache, generateInfiniteCase, getCachedInfiniteCase, getInfiniteCaseId } from '../infinite/generator'
import { clearCaseSave, loadCaseSave, saveCase } from '../persistence/caseSave'
import { recordCaseCompletion } from '../persistence/completion'
import { INFINITE_SESSION_KEY, clearInfiniteSession, loadInfiniteSession, markInfiniteSessionCompleted, startInfiniteSession } from '../persistence/infiniteSession'
import { isCaseCompleted } from '../persistence/progress'
import { findKiller } from '../rules'
import { solveCase } from '../solver'
import { validateCaseDefinition } from '../validation'
const storage = () => { const values = new Map<string, string>(); return { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (key: string) => values.delete(key), clear: () => values.clear(), key: () => null, get length() { return values.size } } as Storage }
const progress = { saveVersion: 1 as const, selectedDifficulty: 1 as const, completedCaseNumbersByDifficulty: { 1: [], 2: [], 3: [], 4: [], 5: [] } }
const negative = (type: string) => type === 'notZone' || type === 'notOnObject' || type === 'notBesideObject'
describe('infinite', () => {
  it('persists completed sessions without overwrite and rejects locked tiers', () => { const memory = storage(); expect(startInfiniteSession(2, 12, progress, memory)).toBeNull(); expect(startInfiniteSession(1, 123, progress, memory)?.seed).toBe(123); expect(markInfiniteSessionCompleted(memory)?.status).toBe('completed'); expect(startInfiniteSession(1, 456, progress, memory)).toMatchObject({ seed: 123, status: 'completed' }); clearInfiniteSession(memory); expect(loadInfiniteSession(memory)).toBeNull() })
  it('sanitises every invalid session shape', () => { const memory = storage(); for (const value of ['{', JSON.stringify({ saveVersion: 2 }), JSON.stringify({ saveVersion: 1, generationVersion: 2, difficulty: 1, seed: 1, status: 'active' }), JSON.stringify({ saveVersion: 1, generationVersion: 1, difficulty: 0, seed: 1, status: 'active' }), JSON.stringify({ saveVersion: 1, generationVersion: 1, difficulty: 6, seed: 1, status: 'active' }), JSON.stringify({ saveVersion: 1, generationVersion: 1, difficulty: 1, seed: -1, status: 'active' }), JSON.stringify({ saveVersion: 1, generationVersion: 1, difficulty: 1, seed: 4294967296, status: 'active' }), JSON.stringify({ saveVersion: 1, generationVersion: 1, difficulty: 1, seed: 1.2, status: 'active' }), JSON.stringify({ saveVersion: 1, generationVersion: 1, difficulty: 1, seed: 1, status: 'other' })]) { memory.setItem(INFINITE_SESSION_KEY, value); expect(loadInfiniteSession(memory)).toBeNull() } })
  it.each([1,2,3,4,5] as const)('generates valid, readable difficulty %s', difficulty => { const generated = generateInfiniteCase({ difficulty, seed: 12345 + difficulty }), preset = getDifficultyPreset(difficulty), clues = generated.caseData.characters.flatMap(character => character.clues); expect(generated.caseData.rows).toBe(preset.rows); expect(generated.caseData.columns).toBe(preset.columns); expect(generated.caseData.characters).toHaveLength(preset.characterCount); expect(generated.caseData.solution).toHaveLength(preset.characterCount); expect(generated.caseData.characters.every(character => character.clues.length >= 2 && character.clues.some(clue => !negative(clue.type)) && !(character.clues.some(clue => clue.type === 'row') && character.clues.some(clue => clue.type === 'column')))).toBe(true); expect(clues.filter(clue => negative(clue.type)).length / clues.length).toBeLessThanOrEqual(.4); expect(validateCaseDefinition(generated.caseData)).toEqual([]); expect(solveCase(generated.caseData).solutionsFound).toBe(1); expect(analyzeCase(generated.caseData)).toMatchObject({ status: 'unique', matchesCanonical: true }); expect(findKiller(generated.caseData, generated.caseData.solution)?.id).toBe(generated.killerId) })
  it('is deterministic, uses distinct IDs and caches', () => { const first = generateInfiniteCase({ difficulty: 3, seed: 123456 }), again = generateInfiniteCase({ difficulty: 3, seed: 123456 }); expect(again).toEqual(first); expect(getInfiniteCaseId(3, 123)).toBe(getInfiniteCaseId(3, 123)); expect(getInfiniteCaseId(3, 123)).not.toBe(getInfiniteCaseId(5, 123)); expect(getInfiniteCaseId(3, 123)).not.toBe(getInfiniteCaseId(3, 124)); clearInfiniteCaseCache(); const a = getCachedInfiniteCase({ difficulty: 5, seed: 123 }), b = getCachedInfiniteCase({ difficulty: 5, seed: 123 }); expect(a).toBe(b); clearInfiniteCaseCache(); expect(getCachedInfiniteCase({ difficulty: 5, seed: 123 })).not.toBe(a) })
  it('clears case saves and never writes global progress when disabled', () => { const memory = storage(); saveCase('infinite-d3-s123', { placements: [], manualExcludedCells: [{ row: 1, column: 1 }] }, memory); clearCaseSave('infinite-d3-s123', memory); expect(loadCaseSave('infinite-d3-s123', memory)).toEqual({ saveVersion: 2, placements: [], manualExcludedCells: [] }); recordCaseCompletion('infinite-d3-s123', false, memory); expect(isCaseCompleted('infinite-d3-s123', memory)).toBe(false) })
})
