import { describe, expect, it } from 'vitest'
import { evaluateClue } from '../clues'
import { evaluateGlobalClue } from '../globalClues'
import type { GameCase } from '../types'
import { validateCaseDefinition } from '../validation'

const game = (): GameCase => ({ id: 'manual-clues', title: 'Manual', intro: '', difficulty: 1, rows: 3, columns: 3, zones: [{ id: 'carpet', name: 'Carpet', tone: 'unknown', surface: 'carpet' }, { id: 'wood', name: 'Wood', tone: 'cafe' }], board: [
  { row: 1, column: 1, zoneId: 'carpet', occupiable: true }, { row: 1, column: 2, zoneId: 'carpet', occupiable: false, object: { id: 'tv', label: 'TV', icon: '', occupiable: false } }, { row: 1, column: 3, zoneId: 'wood', occupiable: true },
  { row: 2, column: 1, zoneId: 'carpet', occupiable: true }, { row: 2, column: 2, zoneId: 'carpet', occupiable: true, object: { id: 'tv', label: 'TV', icon: '', occupiable: true } }, { row: 2, column: 3, zoneId: 'wood', occupiable: true },
  { row: 3, column: 1, zoneId: 'carpet', occupiable: true }, { row: 3, column: 2, zoneId: 'wood', occupiable: true }, { row: 3, column: 3, zoneId: 'wood', occupiable: true },
], characters: [{ id: 'a', name: 'A', avatar: '', isVictim: false, clues: [] }, { id: 'b', name: 'B', avatar: '', isVictim: true, clues: [] }, { id: 'c', name: 'C', avatar: '', isVictim: false, clues: [] }], solution: [{ characterId: 'a', position: { row: 1, column: 1 } }, { characterId: 'b', position: { row: 2, column: 2 } }, { characterId: 'c', position: { row: 3, column: 3 } }] })

describe('manual-design clue primitives', () => {
  it('evaluates same-column, all diagonal directions and surface anchors', () => { const data = game(), at = (row: number, column: number) => [{ characterId: 'a', position: { row, column } }]; expect(evaluateClue({ id: 'column', type: 'sameColumnAsObject', objectId: 'tv', zoneRelation: 'same', text: '' }, 'a', data, at(2, 2))).toBe('satisfied'); expect(evaluateClue({ id: 'different', type: 'sameColumnAsObject', objectId: 'tv', zoneRelation: 'different', text: '' }, 'a', data, at(3, 2))).toBe('satisfied'); for (const [direction, row, column] of [['northWest', 1, 1], ['northEast', 1, 3], ['southWest', 3, 1], ['southEast', 3, 3]] as const) expect(evaluateClue({ id: direction, type: 'relativeToObject', objectId: 'tv', direction, zoneRelation: 'any', text: '' }, 'a', data, at(row, column))).toBe('satisfied'); expect(evaluateClue({ id: 'surface', type: 'onSurface', surface: 'carpet', text: '' }, 'a', data, at(1, 1))).toBe('satisfied'); expect(evaluateClue({ id: 'tone', type: 'onSurface', surface: 'wood', text: '' }, 'a', data, at(1, 3))).toBe('satisfied') })
  it('uses monotonic surface occupancy and validates invalid manual parameters', () => { const data = game(), clue = { id: 'surface-count', type: 'surfaceOccupancyCount' as const, surface: 'carpet' as const, count: 1, text: '' }; expect(evaluateGlobalClue(clue, data, [])).toBe('undetermined'); expect(evaluateGlobalClue(clue, data, data.solution.slice(0, 2))).toBe('violated'); expect(evaluateGlobalClue(clue, data, [{ characterId: 'a', position: { row: 1, column: 1 } }, { characterId: 'b', position: { row: 2, column: 3 } }, { characterId: 'c', position: { row: 3, column: 2 } }])).toBe('satisfied'); const invalid = game(); invalid.characters[0].clues = [{ id: 'bad', type: 'relativeToObject', objectId: 'missing', direction: 'northEast', zoneRelation: 'bad' as never, text: '' }]; invalid.globalClues = [{ id: 'bad-count', type: 'surfaceOccupancyCount', surface: 'carpet', count: -1, text: '' }]; expect(validateCaseDefinition(invalid).length).toBeGreaterThan(0); expect(invalid.characters.find(character => character.isVictim)?.clues).toEqual([]) })
})
