import { describe, expect, it } from 'vitest'
import { NORMAL_CASE_COUNT, NORMAL_DIFFICULTY_COUNT, NORMAL_TOTAL_CASE_COUNT, NORMAL_UNLOCK_CASE_COUNT } from '../normal/constants'
import { NORMAL_PROGRESS_KEY, getUnlockedDifficulties, isDifficultyUnlocked, loadNormalProgress, markNormalCaseCompleted } from '../persistence/normalProgress'
import { ACHIEVEMENT_PROGRESS_KEY, loadAchievementProgress } from '../persistence/achievementProgress'

class MemoryStorage { private values = new Map<string, string>(); getItem(key: string) { return this.values.get(key) ?? null }; setItem(key: string, value: string) { this.values.set(key, value) } }

describe('normal campaign of fifteen cases', () => {
  it('centralises the active campaign size', () => expect([NORMAL_CASE_COUNT, NORMAL_DIFFICULTY_COUNT, NORMAL_TOTAL_CASE_COUNT, NORMAL_UNLOCK_CASE_COUNT]).toEqual([15, 5, 75, 15]))
  it('migrates V1 progress, drops historical numbers and falls back to the highest unlocked difficulty', () => { const storage = new MemoryStorage() as unknown as Storage; storage.setItem(NORMAL_PROGRESS_KEY, JSON.stringify({ saveVersion: 1, selectedDifficulty: 5, completedCaseNumbersByDifficulty: { 1: Array.from({ length: 80 }, (_, index) => index + 1), 2: [1, 2, 16], 3: [], 4: [], 5: [] } })); const progress = loadNormalProgress(storage); expect(progress).toMatchObject({ saveVersion: 2, selectedDifficulty: 2 }); expect(progress.completedCaseNumbersByDifficulty[1]).toHaveLength(15); expect(progress.completedCaseNumbersByDifficulty[2]).toEqual([1, 2]) })
  it('unlocks each tier only after all fifteen active cases and rejects locked or historical completion writes', () => { const storage = new MemoryStorage() as unknown as Storage; expect(markNormalCaseCompleted(2, 1, storage).completedCaseNumbersByDifficulty[2]).toEqual([]); for (let number = 1; number <= 14; number += 1) markNormalCaseCompleted(1, number, storage); expect(isDifficultyUnlocked(2, loadNormalProgress(storage))).toBe(false); markNormalCaseCompleted(1, 15, storage); expect(getUnlockedDifficulties(loadNormalProgress(storage))).toEqual([1, 2]); expect(markNormalCaseCompleted(1, 16, storage).completedCaseNumbersByDifficulty[1]).toHaveLength(15) })
  it('migrates the historical archive achievement once while retaining its earliest date', () => { const storage = new MemoryStorage() as unknown as Storage; storage.setItem(ACHIEVEMENT_PROGRESS_KEY, JSON.stringify({ saveVersion: 1, unlocked: [{ id: 'normal-all-400', unlockedAt: '2026-01-02T00:00:00Z' }, { id: 'normal-all-75', unlockedAt: '2026-01-01T00:00:00Z' }] })); expect(loadAchievementProgress(storage).unlocked).toEqual([{ id: 'normal-all-75', unlockedAt: '2026-01-01T00:00:00Z' }]) })
  it.each([0, 3, 999, undefined, '2'])('rejects unsupported Normal progress version %s', version => { const storage = new MemoryStorage() as unknown as Storage; storage.setItem(NORMAL_PROGRESS_KEY, JSON.stringify({ saveVersion: version, selectedDifficulty: 5, completedCaseNumbersByDifficulty: { 1: [1] } })); expect(loadNormalProgress(storage)).toEqual({ saveVersion: 2, selectedDifficulty: 1, completedCaseNumbersByDifficulty: { 1: [], 2: [], 3: [], 4: [], 5: [] } }) })
})
