import { describe, expect, it } from 'vitest'
import { formatDifficultyStars, isDifficultyRating } from '../difficulty'
import { getAutomaticExcludedCells, mergeExcludedCells } from '../exclusions'
import { loadCaseSave, saveCase } from '../persistence/caseSave'
import { isCaseCompleted, loadProgress, markCaseCompleted } from '../persistence/progress'
import { loadSettings, updateSettings } from '../persistence/settings'
import { case001 } from '../../data/cases/case001'
import { createScenarioProfile } from '../generation/scenario/profile'
import { validateGenerationTemplate, validateScenarioProfile } from '../generation/scenario/validation'
import { createGenerationTemplate } from '../generation/template'
import { validateCaseDefinition } from '../validation'
const memory = () => { const data = new Map<string, string>(); return { getItem: (key: string) => data.get(key) ?? null, setItem: (key: string, value: string) => data.set(key, value), removeItem: (key: string) => data.delete(key), clear: () => data.clear(), key: () => null, get length() { return data.size } } as Storage }
describe('FASE 4A.1', () => {
  it('valida dificultad y formatea estrellas', () => { expect([1,2,3,4,5].every(isDifficultyRating)).toBe(true); expect([0,6,-1,1.5,'1',NaN,Infinity].some(isDifficultyRating)).toBe(false); expect(formatDifficultyStars(1)).toBe('★'); expect(formatDifficultyStars(3)).toBe('★★★'); expect(formatDifficultyStars(5)).toBe('★★★★★') })
  it('deriva autodesmarque exacto y fusiona sin mutar', () => { const board = Array.from({ length: 9 }, (_, i) => ({ row: Math.floor(i / 3) + 1, column: i % 3 + 1, zoneId: 'z', occupiable: i !== 1 })); expect(getAutomaticExcludedCells(board, [{ characterId: 'a', position: { row: 2, column: 2 } }])).toEqual([{ row: 2, column: 1 }, { row: 2, column: 3 }, { row: 3, column: 2 }]); const many = getAutomaticExcludedCells(board.map(cell => ({ ...cell, occupiable: true })), [{ characterId: 'a', position: { row: 1, column: 1 } }, { characterId: 'b', position: { row: 3, column: 3 } }]); expect(new Set(many.map(item => `${item.row}:${item.column}`)).size).toBe(many.length); expect(many.some(item => item.row === 1 && item.column === 1 || item.row === 3 && item.column === 3)).toBe(false); const manual = [{ row: 1, column: 1 }], auto = [{ row: 1, column: 1 }, { row: 1, column: 2 }]; expect(mergeExcludedCells(manual, auto)).toHaveLength(2); expect(manual).toEqual([{ row: 1, column: 1 }]) })
  it('acepta solo saves V1/V2 y migra V1', () => { const s = memory(); s.setItem('mystery-cases-case001', JSON.stringify({ saveVersion: 1, placements: [], excludedCells: [{ row: 1, column: 1 }] })); expect(loadCaseSave('case001', s).manualExcludedCells).toEqual([{ row: 1, column: 1 }]); saveCase('case001', { placements: [], manualExcludedCells: [{ row: 2, column: 2 }] }, s); expect(JSON.parse(s.getItem('mystery-cases-case001') ?? '{}')).toEqual({ saveVersion: 2, placements: [], manualExcludedCells: [{ row: 2, column: 2 }] }); for (const version of [3,999,'2']) { s.setItem('mystery-cases-case001', JSON.stringify({ saveVersion: version, placements: [] })); expect(loadCaseSave('case001', s).placements).toEqual([]) } })
  it('hace round-trip V2 sin compartir referencias', () => { const s = memory(); const placements = [{ characterId: 'a', position: { row: 1, column: 1 } }], excluded = [{ row: 2, column: 2 }]; saveCase('roundtrip', { placements, manualExcludedCells: excluded }, s); const loaded = loadCaseSave('roundtrip', s); expect(loaded).toEqual({ saveVersion: 2, placements, manualExcludedCells: excluded }); expect(loaded.placements).not.toBe(placements); expect(loaded.manualExcludedCells).not.toBe(excluded); loaded.placements[0].position.row = 9; expect(placements[0].position.row).toBe(1) })
  it('devuelve save vacío ante cualquier corrupción o versión desconocida', () => { const s = memory(); for (const value of ['{', 'null', '{}', JSON.stringify({ saveVersion: 2, placements: {} }), JSON.stringify({ saveVersion: 3, placements: [] }), JSON.stringify({ saveVersion: 999, placements: [] }), JSON.stringify({ saveVersion: '2', placements: [] })]) { s.setItem('mystery-cases-case001', value); expect(loadCaseSave('case001', s)).toEqual({ saveVersion: 2, placements: [], manualExcludedCells: [] }) } })
  it('protege settings y progreso corruptos', () => { const s = memory(); s.setItem('mystery-cases-settings', '{'); expect(loadSettings(s)).toMatchObject({ theme: 'dark', autoCrossout: false, saveVersion: 1 }); updateSettings({ theme: 'light', autoCrossout: true }, s); updateSettings({ theme: 'dark' }, s); expect(loadSettings(s).autoCrossout).toBe(true); markCaseCompleted('case001', s); markCaseCompleted('case001', s); markCaseCompleted('case002', s); expect(loadProgress(s).completedCaseIds).toEqual(['case001','case002']); expect(isCaseCompleted('case001', s)).toBe(true) })
  it('rechaza progreso corrupto y filtra entradas inválidas', () => { const s = memory(); for (const value of ['{', JSON.stringify({ completedCaseIds: 'case001' }), JSON.stringify({ completedCaseIds: ['case001', 123, 'case001', null] })]) { s.setItem('mystery-cases-progress', value); if (value.includes('123')) expect(loadProgress(s).completedCaseIds).toEqual(['case001']); else expect(loadProgress(s)).toEqual({ saveVersion: 1, completedCaseIds: [] }) } })
  it('rechaza difficulty inválida en las validaciones', () => { const invalid = { ...case001, difficulty: 6 } as unknown as typeof case001; expect(validateCaseDefinition(invalid)).toContain('La dificultad debe ser un valor entre 1 y 5.'); const profile = { ...createScenarioProfile(case001), difficulty: 0 } as unknown as ReturnType<typeof createScenarioProfile>; expect(validateScenarioProfile(profile)).toContain('La dificultad debe ser un valor entre 1 y 5.'); const template = createGenerationTemplate(invalid); expect(validateGenerationTemplate(template)).toContain('La dificultad debe ser un valor entre 1 y 5.') })
})
