import { describe, expect, it } from 'vitest'
import { formatDifficultyStars } from '../difficulty'
import { getAutomaticExcludedCells, mergeExcludedCells } from '../exclusions'
import { loadCaseSave } from '../persistence/caseSave'
import { isCaseCompleted, loadProgress, markCaseCompleted } from '../persistence/progress'
import { loadSettings, updateSettings } from '../persistence/settings'

const storage = () => { const values = new Map<string, string>(); return { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { values.set(key, value) }, removeItem: (key: string) => { values.delete(key) }, clear: () => values.clear(), key: () => null, get length() { return values.size } } as Storage }
describe('phase 4 helpers', () => { it('formatea dificultad', () => { expect(formatDifficultyStars(1)).toBe('★'); expect(formatDifficultyStars(3)).toBe('★★★'); expect(formatDifficultyStars(5)).toBe('★★★★★') }); it('deriva exclusiones sin bloqueadas ni ocupadas', () => { const board = Array.from({ length: 9 }, (_, index) => ({ row: Math.floor(index / 3) + 1, column: index % 3 + 1, zoneId: 'z', occupiable: index !== 1 })); expect(getAutomaticExcludedCells(board, [{ characterId: 'a', position: { row: 2, column: 2 } }])).toEqual([{ row: 2, column: 1 }, { row: 2, column: 3 }, { row: 3, column: 2 }]); expect(mergeExcludedCells([{ row: 1, column: 1 }], [{ row: 1, column: 1 }, { row: 1, column: 2 }])).toHaveLength(2) }); it('migra save v1 y conserva settings/progreso', () => { const s = storage(); s.setItem('mystery-cases-case001', JSON.stringify({ saveVersion: 1, placements: [{ characterId: 'a', position: { row: 1, column: 1 } }], excludedCells: [{ row: 1, column: 2 }] })); expect(loadCaseSave('case001', s).manualExcludedCells).toEqual([{ row: 1, column: 2 }]); s.setItem('mystery-cases-settings', JSON.stringify({ theme: 'light' })); expect(updateSettings({ autoCrossout: true }, s)).toMatchObject({ theme: 'light', autoCrossout: true }); markCaseCompleted('case001', s); markCaseCompleted('case001', s); expect(isCaseCompleted('case001', s)).toBe(true); expect(loadProgress(s).completedCaseIds).toHaveLength(1); expect(loadSettings(s).autoCrossout).toBe(true) }) })
