import { describe, expect, it } from 'vitest'
import { analyzeCase } from '../analysis'
import { generatePuzzle } from '../generation/generator'
import { generateValidPlacement } from '../generation/placement'
import { createSeededRandom } from '../generation/random'
import { placeScenarioObjects } from '../generation/scenario/objects'
import { createScenarioProfile } from '../generation/scenario/profile'
import { generateScenarioTemplate } from '../generation/scenario/generator'
import { isZoneConnected, validateGenerationTemplate } from '../generation/scenario/validation'
import type { ScenarioProfile } from '../generation/scenario/types'
import { findKiller, placementsEqual } from '../rules'
import { solveCase } from '../solver'
import { validateCaseDefinition } from '../validation'
import { case001 } from '../../data/cases/case001'

const profile = () => createScenarioProfile(case001)
const zoneSizes = (scenario: ReturnType<typeof generateScenarioTemplate>) => new Map(scenario.template.zones.map(zone => [zone.id, scenario.template.board.filter(cell => cell.zoneId === zone.id).length]))
describe('scenario generation', () => {
  it('crea un profile sin posiciones, pistas ni solución y con catálogo deduplicado', () => { const result = profile(); expect(result.characters).toHaveLength(6); expect(result.zones).toHaveLength(4); expect(result.objects.map(object => object.id).sort()).toEqual(['chair', 'crate', 'plant', 'puddle', 'register', 'table']) })
  it('es reproducible para la misma seed y difiere para seeds verificadas', () => { const first = generateScenarioTemplate(profile(), { seed: 12345 }); const second = generateScenarioTemplate(profile(), { seed: 12345 }); const different = generateScenarioTemplate(profile(), { seed: 67890 }); expect(first.template).toEqual(second.template); expect(first.template.id).toBe(second.template.id); expect(first.template.board).not.toEqual(different.template.board) })
  it.each([1, 2, 3, 10, 42])('genera zonas conectadas y con tamaño mínimo para seed %s', seed => { const scenario = generateScenarioTemplate(profile(), { seed }); expect(validateGenerationTemplate(scenario.template)).toEqual([]); for (const zone of scenario.template.zones) { expect(isZoneConnected(scenario.template.board, zone.id)).toBe(true); expect(zoneSizes(scenario).get(zone.id)).toBeGreaterThanOrEqual(4); expect(scenario.template.board.filter(cell => cell.zoneId === zone.id && cell.occupiable).length).toBeGreaterThanOrEqual(2) } })
  it('coloca el catálogo sin solapamientos y respeta occupiable', () => { const source = profile(); const before = structuredClone(source); const caseBefore = structuredClone(case001); const scenario = generateScenarioTemplate(source, { seed: 12345 }); const objectCells = scenario.template.board.filter(cell => cell.object); expect(objectCells).toHaveLength(source.objects.length); expect(new Set(objectCells.map(cell => `${cell.row}:${cell.column}`)).size).toBe(objectCells.length); expect(new Set(objectCells.map(cell => cell.object?.id)).size).toBe(objectCells.length); for (const cell of objectCells) { expect(cell.object && cell.occupiable === cell.object.occupiable).toBe(true); expect(source.objects.some(object => object.id === cell.object?.id)).toBe(true) }; expect(source).toEqual(before); expect(case001).toEqual(caseBefore) })
  it('acepta objectCount reducido', () => expect(generateScenarioTemplate(profile(), { seed: 12345, objectCount: 2 }).stats.objectsPlaced).toBe(2))
  it('conserva los intentos cuando no puede terminar de colocar objetos', () => { const result = placeScenarioObjects([{ row: 1, column: 1, zoneId: 'only', occupiable: true }], [{ id: 'first', label: 'First', icon: '', occupiable: false }, { id: 'second', label: 'Second', icon: '', occupiable: true }], createSeededRandom(1), 0); expect(result.ok).toBe(false); expect(result.attempts).toBeGreaterThan(0) })
  it.each([1, 2, 42, 12345])('usa el mismo placement inicial que FASE 3A para seed %s', seed => { const scenario = generateScenarioTemplate(profile(), { seed }); const directPlacement = generateValidPlacement(scenario.template, createSeededRandom(seed), 10000); const generated = generatePuzzle(scenario.template, { seed, maxPlacementAttempts: 10000 }); expect(placementsEqual(directPlacement.solution, generated.caseData.solution)).toBe(true); const analysis = analyzeCase(generated.caseData); expect(analysis.status).toBe('unique'); expect(analysis.matchesCanonical).toBe(true); expect(findKiller(generated.caseData, generated.caseData.solution)).not.toBeNull() })
  it.each([1, 2, 42])('funciona end-to-end con FASE 3A para seed %s', seed => { const scenario = generateScenarioTemplate(profile(), { seed }); const generated = generatePuzzle(scenario.template, { seed }); expect(validateCaseDefinition(generated.caseData)).toEqual([]); expect(solveCase(generated.caseData).solutionsFound).toBe(1); const analysis = analyzeCase(generated.caseData); expect(analysis.status).toBe('unique'); expect(analysis.matchesCanonical).toBe(true); expect(findKiller(generated.caseData, generated.caseData.solution)).not.toBeNull() })
  it.each([{ seed: -1 }, { seed: 1.5 }, { seed: Number.NaN }, { seed: Number.POSITIVE_INFINITY }, { maxScenarioAttempts: 0 }, { maxScenarioAttempts: 1.5 }, { maxScenarioAttempts: Number.NaN }, { minZoneCells: 0 }, { minZoneCells: 1.5 }, { minOccupiableCellsPerZone: 0 }, { minOccupiableCellsPerZone: 1.5 }, { objectCount: -1 }, { objectCount: 1.5 }, { objectCount: 99 }])('rechaza opciones inválidas', options => expect(() => generateScenarioTemplate(profile(), { seed: 1, ...options })).toThrow())
  it('rechaza una geometría imposible y un escenario sin asesino posible', () => { expect(() => generateScenarioTemplate(profile(), { seed: 1, minZoneCells: 10 })).toThrow('minZoneCells is impossible'); const impossible: ScenarioProfile = { id: 'impossible', title: '', intro: '', difficulty: 1, rows: 3, columns: 3, zones: [{ id: 'one', name: 'One', tone: 'one' }], objects: [], characters: [{ id: 'v', name: 'V', avatar: '', isVictim: true }, { id: 'a', name: 'A', avatar: '', isVictim: false }, { id: 'b', name: 'B', avatar: '', isVictim: false }] }; expect(() => generateScenarioTemplate(impossible, { seed: 1, maxScenarioAttempts: 2 })).toThrow('Unable to generate a valid scenario template.') })
})
