import type { BoardCell } from '../../types'
import { isDifficultyRating } from '../../difficulty'
import type { GenerationTemplate } from '../types'
import type { ScenarioProfile } from './types'
const key = (row: number, column: number) => `${row}:${column}`
const unique = (items: readonly { id: string }[], label: string, errors: string[]) => { const ids = new Set<string>(); for (const item of items) { if (!item.id) errors.push(`${label} con ID vacío.`); if (ids.has(item.id)) errors.push(`ID de ${label} duplicado: ${item.id}.`); ids.add(item.id) } }
export function isZoneConnected(board: readonly BoardCell[], zoneId: string): boolean { const cells = board.filter(cell => cell.zoneId === zoneId); if (cells.length === 0) return false; const remaining = new Set(cells.map(cell => key(cell.row, cell.column))); const start = cells[0]; const queue = [start]; remaining.delete(key(start.row, start.column)); while (queue.length > 0) { const cell = queue.shift(); if (!cell) break; for (const neighbor of [[cell.row - 1, cell.column], [cell.row + 1, cell.column], [cell.row, cell.column - 1], [cell.row, cell.column + 1]]) { const neighborKey = key(neighbor[0], neighbor[1]); if (!remaining.has(neighborKey)) continue; remaining.delete(neighborKey); const next = cells.find(candidate => candidate.row === neighbor[0] && candidate.column === neighbor[1]); if (next) queue.push(next) } } return remaining.size === 0 }
export function validateScenarioProfile(profile: ScenarioProfile): string[] { const errors: string[] = []; if (!isDifficultyRating(profile.difficulty)) errors.push('La dificultad debe ser un valor entre 1 y 5.'); if (profile.rows <= 0) errors.push('rows debe ser mayor que 0.'); if (profile.columns <= 0) errors.push('columns debe ser mayor que 0.'); if (profile.characters.length !== profile.rows || profile.characters.length !== profile.columns) errors.push('Los personajes deben coincidir con rows y columns.'); if (profile.characters.filter(character => character.isVictim).length !== 1) errors.push('El profile debe tener exactamente una víctima.'); unique(profile.characters, 'personaje', errors); if (profile.zones.length === 0) errors.push('El profile debe tener al menos una zona.'); unique(profile.zones, 'zona', errors); unique(profile.objects, 'objeto', errors); for (const object of profile.objects) if (!object.label || typeof object.icon !== 'string' || typeof object.occupiable !== 'boolean') errors.push(`Objeto inválido: ${object.id}.`); return errors }
export function validateGenerationTemplate(template: GenerationTemplate): string[] { const errors: string[] = []; if (!isDifficultyRating(template.difficulty)) errors.push('La dificultad debe ser un valor entre 1 y 5.'); if (template.rows <= 0) errors.push('rows debe ser mayor que 0.'); if (template.columns <= 0) errors.push('columns debe ser mayor que 0.'); if (template.characters.length !== template.rows || template.characters.length !== template.columns) errors.push('Los personajes deben coincidir con rows y columns.'); if (template.characters.filter(character => character.isVictim).length !== 1) errors.push('La plantilla debe tener exactamente una víctima.'); unique(template.characters, 'personaje', errors); unique(template.zones, 'zona', errors); if (template.board.length !== template.rows * template.columns) errors.push('El tablero no contiene rows * columns celdas.'); const zoneIds = new Set(template.zones.map(zone => zone.id)); const seen = new Set<string>(); for (const cell of template.board) { const coordinate = key(cell.row, cell.column); if (seen.has(coordinate)) errors.push(`Coordenada duplicada: ${coordinate}.`); seen.add(coordinate); if (cell.row < 1 || cell.row > template.rows || cell.column < 1 || cell.column > template.columns) errors.push(`Coordenada fuera de rango: ${coordinate}.`); if (!zoneIds.has(cell.zoneId)) errors.push(`Zona inexistente en ${coordinate}: ${cell.zoneId}.`); if (cell.object && cell.occupiable !== cell.object.occupiable) errors.push(`Incoherencia occupiable en ${coordinate}.`); if (cell.object && (!cell.object.id || !cell.object.label || typeof cell.object.icon !== 'string' || typeof cell.object.occupiable !== 'boolean')) errors.push(`Objeto inválido en ${coordinate}.`) }
  for (const zone of template.zones) { if (!template.board.some(cell => cell.zoneId === zone.id)) errors.push(`La zona no aparece en el tablero: ${zone.id}.`); else if (!isZoneConnected(template.board, zone.id)) errors.push(`La zona no es ortogonalmente conectada: ${zone.id}.`) }
  return errors }
