import type { Placement, Position } from '../types'
export interface HintUsage { review: number; exclusion: number; reveal: number }
export interface CaseSave { saveVersion: 3; placements: Placement[]; manualExcludedCells: Position[]; hintsUsed: HintUsage }
const hints = (): HintUsage => ({ review: 0, exclusion: 0, reveal: 0 })
const empty = (): CaseSave => ({ saveVersion: 3, placements: [], manualExcludedCells: [], hintsUsed: hints() })
export const getCaseSaveKey = (caseId: string) => `mystery-cases-${caseId}`
export function loadCaseSave(caseId: string, storage: Storage = localStorage): CaseSave { try { const value: unknown = JSON.parse(storage.getItem(getCaseSaveKey(caseId)) ?? 'null'); if (!value || typeof value !== 'object') return empty(); const save = value as { saveVersion?: unknown; placements?: unknown; excludedCells?: unknown; manualExcludedCells?: unknown; hintsUsed?: Partial<HintUsage> }; if (![1,2,3].includes(save.saveVersion as number) || !Array.isArray(save.placements)) return empty(); const positions = (items: unknown): Position[] => Array.isArray(items) ? items.filter((item): item is Position => typeof item === 'object' && item !== null && typeof (item as Position).row === 'number' && typeof (item as Position).column === 'number').map(item => ({ ...item })) : []; const placements = save.placements.filter((item): item is Placement => typeof item === 'object' && item !== null && typeof (item as Placement).characterId === 'string' && typeof (item as Placement).position?.row === 'number' && typeof (item as Placement).position?.column === 'number').map(item => ({ characterId: item.characterId, position: { ...item.position } })); const usage = save.saveVersion === 3 && save.hintsUsed && [save.hintsUsed.review, save.hintsUsed.exclusion, save.hintsUsed.reveal].every(value => Number.isInteger(value) && (value as number) >= 0) ? save.hintsUsed as HintUsage : hints(); return { saveVersion: 3, placements, manualExcludedCells: positions(save.saveVersion === 1 ? save.excludedCells : save.manualExcludedCells), hintsUsed: { ...usage } } } catch { return empty() } }
export function saveCase(caseId: string, save: Omit<CaseSave, 'saveVersion' | 'hintsUsed'> & { hintsUsed?: HintUsage }, storage: Storage = localStorage) { storage.setItem(getCaseSaveKey(caseId), JSON.stringify({ saveVersion: 3, placements: save.placements.map(item => ({ characterId: item.characterId, position: { ...item.position } })), manualExcludedCells: save.manualExcludedCells.map(item => ({ ...item })), hintsUsed: { ...(save.hintsUsed ?? hints()) } })) }
export function clearCaseSave(caseId: string, storage: Storage = localStorage) { storage.removeItem(getCaseSaveKey(caseId)) }
