import { isDifficultyRating } from '../difficulty'
import type { DifficultyRating } from '../types'

export const INVESTIGATION_HISTORY_KEY = 'mystery-cases-investigation-history'
export type InvestigationMode = 'normal' | 'daily' | 'infinite'
export interface InvestigationAssistUsage { review: number; exclusion: number; positionChecks: number; total: number }
export interface InvestigationRecord { logicalId: string; mode: InvestigationMode; difficulty: DifficultyRating; firstCompletedAt: string; lastCompletedAt: string; completions: number; perfectCompletions: number; lastAssistUsage: InvestigationAssistUsage; bestAssistUsage: InvestigationAssistUsage }
export interface InvestigationHistory { saveVersion: 1; records: InvestigationRecord[] }
export interface InvestigationCompletionInput { logicalId: string; mode: InvestigationMode; difficulty: DifficultyRating; assists: Omit<InvestigationAssistUsage, 'total'> }
const empty = (): InvestigationHistory => ({ saveVersion: 1, records: [] })
const isCounter = (value: unknown): value is number => Number.isInteger(value) && (value as number) >= 0 && Number.isSafeInteger(value)
const validTimestamp = (value: unknown): value is string => typeof value === 'string' && !Number.isNaN(Date.parse(value))
const isMode = (value: unknown): value is InvestigationMode => value === 'normal' || value === 'daily' || value === 'infinite'
const validDailyDate = (value: string) => { const match = /^daily-(\d{4})-(\d{2})-(\d{2})$/.exec(value); if (!match) return false; const [year, month, day] = match.slice(1).map(Number), date = new Date(Date.UTC(year, month - 1, day)); return date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day }
const logicalDifficulty = (logicalId: string, mode: InvestigationMode): DifficultyRating | null => { const match = mode === 'daily' ? null : new RegExp(`^${mode}-d([1-5])-`).exec(logicalId); return match ? Number(match[1]) as DifficultyRating : mode === 'daily' ? null : null }
export const isInvestigationLogicalId = (value: unknown, mode?: InvestigationMode): value is string => {
  if (typeof value !== 'string') return false
  if ((mode === undefined || mode === 'normal') && /^normal-d[1-5]-c(?:0[1-9]|[1-7]\d|80)$/.test(value)) return true
  if ((mode === undefined || mode === 'daily') && validDailyDate(value)) return true
  if ((mode === undefined || mode === 'infinite') && /^infinite-d[1-5]-s(?:0|[1-9]\d*)$/.test(value)) { const seed = Number(value.split('-s')[1]); return Number.isInteger(seed) && seed >= 0 && seed <= 0xffff_ffff }
  return false
}
export const createAssistUsage = (usage: Omit<InvestigationAssistUsage, 'total'>): InvestigationAssistUsage => ({ ...usage, total: usage.review + usage.exclusion + usage.positionChecks })
const validUsage = (value: unknown): value is InvestigationAssistUsage => { if (!value || typeof value !== 'object') return false; const usage = value as InvestigationAssistUsage; return isCounter(usage.review) && isCounter(usage.exclusion) && isCounter(usage.positionChecks) && usage.total === usage.review + usage.exclusion + usage.positionChecks }
const compareUsage = (left: InvestigationAssistUsage, right: InvestigationAssistUsage) => left.total - right.total || left.positionChecks - right.positionChecks || left.exclusion - right.exclusion || left.review - right.review
const validRecordIdentity = (logicalId: string, mode: InvestigationMode, difficulty: DifficultyRating) => { const encoded = logicalDifficulty(logicalId, mode); return encoded === null || encoded === difficulty }
const normaliseRecord = (value: unknown): InvestigationRecord | null => { if (!value || typeof value !== 'object') return null; const record = value as InvestigationRecord; if (!isMode(record.mode) || !isInvestigationLogicalId(record.logicalId, record.mode) || !isDifficultyRating(record.difficulty) || !validRecordIdentity(record.logicalId, record.mode, record.difficulty) || !validTimestamp(record.firstCompletedAt) || !validTimestamp(record.lastCompletedAt) || Date.parse(record.firstCompletedAt) > Date.parse(record.lastCompletedAt) || !isCounter(record.completions) || record.completions < 1 || !isCounter(record.perfectCompletions) || record.perfectCompletions > record.completions || !validUsage(record.lastAssistUsage) || !validUsage(record.bestAssistUsage) || (record.perfectCompletions > 0 && !isPerfectInvestigation(record.bestAssistUsage)) || (isPerfectInvestigation(record.bestAssistUsage) && record.perfectCompletions < 1)) return null; return structuredClone(record) }
const normalise = (value: unknown): InvestigationHistory => { if (!value || typeof value !== 'object' || (value as InvestigationHistory).saveVersion !== 1 || !Array.isArray((value as InvestigationHistory).records)) return empty(); const records = new Map<string, InvestigationRecord>(); for (const item of (value as InvestigationHistory).records) { const record = normaliseRecord(item); if (record && !records.has(record.logicalId)) records.set(record.logicalId, record) } return { saveVersion: 1, records: [...records.values()] } }
export function loadInvestigationHistory(storage: Storage = localStorage): InvestigationHistory { try { return normalise(JSON.parse(storage.getItem(INVESTIGATION_HISTORY_KEY) ?? 'null')) } catch { return empty() } }
export function saveInvestigationHistory(history: InvestigationHistory, storage: Storage = localStorage): InvestigationHistory { const safe = normalise(history); storage.setItem(INVESTIGATION_HISTORY_KEY, JSON.stringify(safe)); return safe }
export function recordInvestigationCompletion(input: InvestigationCompletionInput, storage: Storage = localStorage, now: Date = new Date()): InvestigationHistory { if (!isMode(input.mode) || !isInvestigationLogicalId(input.logicalId, input.mode) || !isDifficultyRating(input.difficulty) || !validRecordIdentity(input.logicalId, input.mode, input.difficulty) || !isCounter(input.assists.review) || !isCounter(input.assists.exclusion) || !isCounter(input.assists.positionChecks) || Number.isNaN(now.getTime())) return loadInvestigationHistory(storage); const history = loadInvestigationHistory(storage), timestamp = now.toISOString(), usage = createAssistUsage(input.assists), perfect = isPerfectInvestigation(usage), index = history.records.findIndex(record => record.logicalId === input.logicalId); if (index < 0) return saveInvestigationHistory({ saveVersion: 1, records: [...history.records, { logicalId: input.logicalId, mode: input.mode, difficulty: input.difficulty, firstCompletedAt: timestamp, lastCompletedAt: timestamp, completions: 1, perfectCompletions: perfect ? 1 : 0, lastAssistUsage: usage, bestAssistUsage: usage }] }, storage); const previous = history.records[index], record = { ...previous, lastCompletedAt: timestamp, completions: previous.completions + 1, perfectCompletions: previous.perfectCompletions + (perfect ? 1 : 0), lastAssistUsage: usage, bestAssistUsage: compareUsage(usage, previous.bestAssistUsage) < 0 ? usage : previous.bestAssistUsage }; return saveInvestigationHistory({ saveVersion: 1, records: history.records.map((item, itemIndex) => itemIndex === index ? record : item) }, storage) }
export const isPerfectInvestigation = (value: InvestigationRecord | InvestigationAssistUsage) => { const usage = 'bestAssistUsage' in value ? value.bestAssistUsage : value; return usage.review === 0 && usage.exclusion === 0 && usage.positionChecks === 0 && usage.total === 0 }
export const countTrackedCompletions = (history: InvestigationHistory) => history.records.reduce((total, record) => total + record.completions, 0)
export const countPerfectInvestigations = (history: InvestigationHistory) => history.records.reduce((total, record) => total + record.perfectCompletions, 0)
export const countPerfectUniqueInvestigations = (history: InvestigationHistory) => history.records.reduce((total, record) => total + (isPerfectInvestigation(record) ? 1 : 0), 0)
export const getBestAssistUsage = (logicalId: string, history: InvestigationHistory) => history.records.find(record => record.logicalId === logicalId)?.bestAssistUsage
export const getRecordsByMode = (mode: InvestigationMode, history: InvestigationHistory) => history.records.filter(record => record.mode === mode)
