import type { NameCatalogEntry } from './types'

const maleNames = ["Antonio","José","Jordi","David","Francisco","Manuel","Marc","Juan","Daniel","Carlos","Joan","Javier","Josep","Jorge","Ramón","Albert","Xavier","Miguel","Pedro","Sergio","Alejandro","Mohamed","Pablo","Luis","Ángel","Rafael","Fernando","Alberto","Diego","Víctor","Adrián","Rubén","Raúl","Iván","Óscar","Enrique","Andrés","Mario","Marcos","Joaquín","Gabriel","Gonzalo","Roberto","Jaime","Eduardo","Ricardo","Álvaro","Samuel","Héctor","Guillermo","Martín","Mateo","Hugo","Lucas","Pau","Pol","Arnau","Oriol","Gerard","Guillem","Martí","Nil","Biel","Àlex","Miquel","Ferran","Carles","Jaume","Lluís","Roger","Sergi","Adrià","Francesc","Pere","Ismael","Cristian","Eric","Nicolás","Bruno","Leo","Iker","Unai","Aitor","Borja","César","Felipe","Vicente","Salvador","Emilio","Agustín","Ignacio","Tomás","Sebastián","Lorenzo","Simón","Joel","Jan","Roc","Aleix","Enric"]
const femaleNames = ["María","Montserrat","Carmen","Marta","Laura","Núria","Cristina","Isabel","Anna","Josefa","Ana","Júlia","Sílvia","Antònia","Francisca","Laia","Sara","Paula","Dolores","Rosa","Pilar","Teresa","Elena","Patricia","Sonia","Raquel","Beatriz","Mercedes","Lucía","Andrea","Claudia","Alba","Irene","Marina","Eva","Natalia","Alicia","Esther","Mónica","Susana","Yolanda","Victoria","Verónica","Rocío","Gemma","Mercè","Neus","Mireia","Meritxell","Judit","Carla","Aina","Mariona","Ona","Ariadna","Berta","Clara","Emma","Jana","Abril","Martina","Noa","Carlota","Alejandra","Sofía","Valeria","Daniela","Adriana","Inés","Lorena","Vanessa","Sandra","Ruth","Gloria","Margarita","Amparo","Paloma","Rebeca","Lidia","Celia","Nerea","Aroa","Elisa","Ángela","Olga","Aurora","Carolina","Miriam","Noelia","Ainhoa","Maite","Maribel","Roser","Carme","Eulàlia","Helena","Elisabet","Queralt","Ivet","Mar"]

const entries = (names: readonly string[], gender: NameCatalogEntry['gender']) => names.map((name, index) => ({ id: `${gender}-${String(index + 1).padStart(3, '0')}`, name, gender }))

export const maleNameCatalog: readonly NameCatalogEntry[] = entries(maleNames, 'male')
export const femaleNameCatalog: readonly NameCatalogEntry[] = entries(femaleNames, 'female')
export const nameCatalog: readonly NameCatalogEntry[] = [...maleNameCatalog, ...femaleNameCatalog]
