import { describe, expect, it } from 'vitest'
import { objectAppearanceCatalog, resolveObjectAppearance } from '../appearanceCatalog'

describe('object appearance catalog', () => {
  it('registers every contextual object with a human label and a supported visual asset', () => {
    expect(Object.keys(objectAppearanceCatalog)).toHaveLength(65)
    for (const appearance of Object.values(objectAppearanceCatalog)) {
      expect(appearance.label.length).toBeGreaterThan(0)
      expect(appearance.src).toMatch(/^(data:image\/svg\+xml|.*\.(png|svg)$)/)
    }
    expect(objectAppearanceCatalog.cafeCounter).toMatchObject({ scale: 0.96, visualProfile: 'wide' })
    expect(objectAppearanceCatalog.gymBench).toMatchObject({ scale: 0.92, visualProfile: 'wide' })
    expect(objectAppearanceCatalog.lifeguardChair).toMatchObject({ scale: 0.86, visualProfile: 'tall' })
    expect(objectAppearanceCatalog.poolSurface).toMatchObject({ renderMode: 'coverFootprint' })
    expect(objectAppearanceCatalog.cargoLoader).toMatchObject({ label: 'Carretilla elevadora', visualProfile: 'wide' })
    expect(objectAppearanceCatalog.magneticPallet).toMatchObject({ label: 'Plataforma de contenedores', visualProfile: 'wide' })
    expect(objectAppearanceCatalog.freightConsole).toMatchObject({ label: 'Consola de control', visualProfile: 'standard' })
    expect(objectAppearanceCatalog.sealedContainer).toMatchObject({ label: 'Caja metálica', visualProfile: 'standard' })
    expect(objectAppearanceCatalog.maintenanceUnit).toMatchObject({ label: 'Robot de mantenimiento', visualProfile: 'tall' })
    expect(objectAppearanceCatalog.xenoLabBench).toMatchObject({ label: 'Mesa de laboratorio', visualProfile: 'wide' })
    expect(objectAppearanceCatalog.specimenTank).toMatchObject({ label: 'Acuario de laboratorio', visualProfile: 'wide' })
    expect(objectAppearanceCatalog.sampleAnalyzer).toMatchObject({ label: 'Máquina de análisis', visualProfile: 'compact' })
    expect(objectAppearanceCatalog.containmentPod).toMatchObject({ label: 'Cápsula de cristal', visualProfile: 'tall' })
    expect(objectAppearanceCatalog.decontaminationArch).toMatchObject({ label: 'Arco de limpieza', visualProfile: 'tall' })
    expect(objectAppearanceCatalog.hydroponicBed).toMatchObject({ label: 'Bancal de plantas', visualProfile: 'wide' })
    expect(objectAppearanceCatalog.growTower).toMatchObject({ label: 'Torre de plantas', visualProfile: 'tall' })
    expect(objectAppearanceCatalog.nutrientTank).toMatchObject({ label: 'Depósito cilíndrico', visualProfile: 'tall' })
    expect(objectAppearanceCatalog.irrigationConsole).toMatchObject({ label: 'Máquina de riego', visualProfile: 'wide' })
    expect(objectAppearanceCatalog.harvestCart).toMatchObject({ label: 'Carro con plantas', visualProfile: 'standard' })
    expect(objectAppearanceCatalog.assemblyLine).toMatchObject({ label: 'Cadena de montaje', visualProfile: 'wide', renderMode: 'coverFootprint' })
    expect(objectAppearanceCatalog.roboticArm).toMatchObject({ label: 'Brazo robótico', visualProfile: 'tall' })
    expect(objectAppearanceCatalog.androidPod).toMatchObject({ label: 'Cápsula de ensamblaje', visualProfile: 'tall' })
    expect(objectAppearanceCatalog.calibrationStation).toMatchObject({ label: 'Estación de calibración', visualProfile: 'wide' })
    expect(objectAppearanceCatalog.partsTrolley).toMatchObject({ label: 'Carro de repuestos', visualProfile: 'standard' })
    expect(objectAppearanceCatalog.lunarDrill).toMatchObject({ label: 'Taladro lunar', visualProfile: 'standard' })
    expect(objectAppearanceCatalog.oreCart).toMatchObject({ label: 'Vagoneta de mineral', visualProfile: 'wide' })
    expect(objectAppearanceCatalog.oreCrusher).toMatchObject({ label: 'Trituradora de mineral', visualProfile: 'tall' })
    expect(objectAppearanceCatalog.surveyConsole).toMatchObject({ label: 'Consola topográfica', visualProfile: 'standard' })
    expect(objectAppearanceCatalog.pressureLocker).toMatchObject({ label: 'Armario presurizado', visualProfile: 'tall' })
    expect(objectAppearanceCatalog.lunarExcavation).toMatchObject({ label: 'Zona de excavación lunar', renderMode: 'coverFootprint' })
  })

  it('uses the explicit appearance while preserving the legacy icon fallback safely', () => {
    const explicit = resolveObjectAppearance({ appearance: 'sunLounger', icon: 'legacy-chair.png', label: 'una silla' })
    expect(explicit).toMatchObject({ label: 'Tumbona' })
    expect(explicit.src).not.toBe('legacy-chair.png')
    expect(resolveObjectAppearance({ icon: 'legacy-chair.png', label: 'una silla' })).toEqual({ src: 'legacy-chair.png', label: 'una silla' })
    expect(resolveObjectAppearance({ appearance: 'unknown' as never, icon: 'legacy-chair.png', label: 'una silla' })).toEqual({ src: 'legacy-chair.png', label: 'una silla' })
  })
})
